import "./globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

import { TRPCReactProvider } from "pnpm/trpc/react";

export const metadata: Metadata = {
  title: "SeniorFit",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <NextTopLoader color="#18181b" shadow={false} showSpinner={false} />
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
